import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <nav>
            <Link href={"/"}>|홈|</Link>
            <Link href={"/article"}>게시글|</Link>
            <Link href={"/user"}>사용자|</Link>
          </nav>

          {children}
      </main>

    </html>
  );
}
